/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author eliu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        btnMateriaPrima = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnSucursales = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnEntrada_Salida_MateriaPrima = new javax.swing.JButton();
        btnEntrada_Salida_Producto = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jLabelMateriaPrima = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabelSucursales = new javax.swing.JLabel();
        jLabelReporte = new javax.swing.JLabel();
        jLabelESProducto = new javax.swing.JLabel();
        jLabelESMateriaPrima = new javax.swing.JLabel();
        jLabelPedidos = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IED");
        setBackground(new java.awt.Color(255, 242, 204));
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 242, 204));

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelMenu.setText("Menú");

        btnMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Harina.png"))); // NOI18N

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Tortillas.png"))); // NOI18N

        btnSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sucursal.png"))); // NOI18N

        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Reporte.png"))); // NOI18N

        btnEntrada_Salida_MateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FlechasYHarina.png"))); // NOI18N

        btnEntrada_Salida_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/FlechasYTortillas.png"))); // NOI18N

        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Pedidos.png"))); // NOI18N

        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salida.png"))); // NOI18N

        jLabelMateriaPrima.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelMateriaPrima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMateriaPrima.setText("Materia Prima");

        jLabelProducto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProducto.setText("Producto");

        jLabelSucursales.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelSucursales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSucursales.setText("Sucursales");

        jLabelReporte.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReporte.setText("Reportes");

        jLabelESProducto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelESProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelESProducto.setText("<html> <p>Entrada/Salida<br/><center>Producto</center></p> </html>    ");

        jLabelESMateriaPrima.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelESMateriaPrima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelESMateriaPrima.setText("<html>\n<p>Entrada/Salida<br/><center>MateriaPrima</center></p>\n</html>\n\n\n\n");

        jLabelPedidos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPedidos.setText("Pedidos");

        jLabelSalir.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setText("Salir");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(btnMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabelMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(19, 19, 19)))
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelSucursales, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btnSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelESMateriaPrima)
                                    .addComponent(btnEntrada_Salida_MateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEntrada_Salida_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabelESProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabelMenu)))
                .addGap(45, 45, 45))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu)
                .addGap(20, 20, 20)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMateriaPrima))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProducto)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSucursales)
                                .addComponent(jLabelReporte)))))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntrada_Salida_MateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrada_Salida_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelESProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelESMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPedidos)
                    .addComponent(jLabelSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada_Salida_MateriaPrima;
    private javax.swing.JButton btnEntrada_Salida_Producto;
    private javax.swing.JButton btnMateriaPrima;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSucursales;
    private javax.swing.JLabel jLabelESMateriaPrima;
    private javax.swing.JLabel jLabelESProducto;
    private javax.swing.JLabel jLabelMateriaPrima;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelPedidos;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelReporte;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelSucursales;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
